language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    include:
        - env: BUILD_TYPE=doc # marker environment variable to make the build matrix more readable in the UI
          # Override the different steps of the build config
          language: python
          before_install: []
          install: pip install Sphinx sphinx_rtd_theme
          before_script: []
          script: sphinx-build -nW -b html -d docs/build/doctrees docs docs/build/html
          after_script: []

env:
    global:
        - BUILD_TYPE=code
        - secure: HhIy0kN0+UbuLeaVBk7O/utAYo038a9Emr8cdcfU+LQTu6CfGEbifH+LddXs6M/bSLTdNUSwQSnwycbeNYZ6iHCO/JI/vEgKxCTSecPerMXBIVCQjFZaCp3Tev8JJ40hKe78WJ/d0G4bGtIR6atR5V+H8Z29iwJeFtCj6doEt3o=
        - secure: oLadQTqg8HSEmUC0qEtChKd/R0ZiFNhzoZjIaa8kAJ0fjln/2xfNCBQIg4YstyjFy2kLiP6Lg8xW/RZljzyTHC+MCB9NNqTYjKLqFNRvFOlZUOnrAwc4sl4qjMYu9klWKa+rfyZzsuVWn++g829s2lFopkImqa6EB9DOR2TOT6w=

addons:
    sauce_connect: true

install:
    - composer require satooshi/php-coveralls:dev-master --dev

before_script:
    - mkdir -p build/logs

script:
    - phpunit -v --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar -t 3
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
